#!/bin/sh

CARD="${1:-0}"
MIXER="${2:-default}"

symbol=$(amixer -c $CARD -M -D $MIXER get Master | grep Playback | grep -q off && echo '' || echo '')

amixer -c $CARD -M -D $MIXER get Master |
        sed -n "s/^[^:]*: Playback [0-9]* \[\([0-9]*%\)\] .*/$symbol \1/p" |
                head -n1
