#!/bin/sh

bn=$(light)
bn=${bn%%.*}
if [ $bn -eq 100 ]
then
	echo "%{+u +o}%{-u -o}━━━━━━━━━━━━━━%{+u +o}%{-u -o}%{F#777777}"
elif [ $bn -gt 91 ]
then
	echo "%{+u +o}%{-u -o}━━━━━━━━━━━━━%{+u +o}%{-u -o}%{F#777777}━%{F#777777}"
elif [ $bn -gt 83 ]
then
	echo "%{+u +o}%{-u -o}━━━━━━━━━━━━%{+u +o}%{-u -o}%{F#777777}━━%{F#777777}"
elif [ $bn -gt 75 ]
then
	echo "%{+u +o}%{-u -o}━━━━━━━━━━━%{+u +o}%{-u -o}%{F#777777}━━━%{F#777777}"
elif [ $bn -gt 67 ]
then
	echo "%{+u +o}%{-u -o}━━━━━━━━━━%{+u +o}%{-u -o}%{F#777777}━━━━%{F#777777}"
elif [ $bn -gt 59 ]
then
	echo "%{+u +o}%{-u -o}━━━━━━━━━%{+u +o}%{-u -o}%{F#777777}━━━━━%{F#777777}"
elif [ $bn -gt 51 ]
then
	echo "%{+u +o}%{-u -o}━━━━━━━━%{+u +o}%{-u -o}%{F#777777}━━━━━━%{F#777777}"
elif [ $bn -gt 43 ]
then
	echo "%{+u +o}%{-u -o}━━━━━━━%{+u +o}%{-u -o}%{F#777777}━━━━━━━%{F#777777}"
elif [ $bn -gt 35 ]
then
	echo "%{+u +o}%{-u -o}━━━━━━%{+u +o}%{-u -o}%{F#777777}━━━━━━━━%{F#777777}"
elif [ $bn -gt 27 ]
then
	echo "%{+u +o}%{-u -o}━━━━━%{+u +o}%{-u -o}%{F#777777}━━━━━━━━━%{F#777777}"
elif [ $bn -gt 19 ]
then
	echo "%{+u +o}%{-u -o}━━━━%{+u +o}%{-u -o}%{F#777777}━━━━━━━━━━%{F#777777}"
elif [ $bn -gt 11 ]
then
	echo "%{+u +o}%{-u -o}━━━%{+u +o}%{-u -o}%{F#777777}━━━━━━━━━━━"
elif [ $bn -gt 3 ]
then
	echo "%{+u +o}%{-u -o}━━%{+u +o}%{-u -o}%{F#777777}━━━━━━━━━━━━"
else
	# if [ $bn -eq 0 ]
	# then
		# echo "%{+u +o}%{-u -o}%{+u +o}%{-u -o}%{F#777777}━━━━━━━━━━━━━━"
	# else
	echo "%{+u +o}%{-u -o}━%{+u +o}%{-u -o}%{F#777777}━━━━━━━━━━━━━"
	# fi
fi
