#!/bin/sh
# OLDCOLOR = 77777794A5BC  3E4958

CARD="${1:-0}"
MIXER="${2:-default}"
trap "echo Booh!" SIGHUP
mute=$(amixer -c $CARD -M -D $MIXER get Master | grep Playback | grep -q off && echo 1 || echo 0)
if [ $mute -eq 1 ]
then
	slider=" %{F#67727E}%{T4}%{T-}━━━━━━━━━━━━━━%{F-}"
else
	# echo "━━━━━━━▊%{F#67727E}━━━━━━━"
	pc=$(amixer -c $CARD -M -D $MIXER get Master |
	echo $(sed -n "s/^[^:]*: Playback [0-9]* \[\([0-9]*%\)\] .*/$symbol \1/p" | head -n1))
	pc=${pc::-1}
	if [ $pc -eq 100 ]
	then
		slider=" %{F#FFFFFF}━━━━━━━━━━━━━━%{T4}%{T-}%{F#67727E}%{F-}"
	elif [ $pc -gt 91 ]
	then
		slider=" %{F#FFFFFF}━━━━━━━━━━━━━%{T4}%{T-}%{F#67727E}━%{F-}"
	elif [ $pc -gt 83 ]
	then
		slider=" %{F#FFFFFF}━━━━━━━━━━━━%{T4}%{T-}%{F#67727E}━━%{F-}"
	elif [ $pc -gt 75 ]
	then
		slider=" %{F#FFFFFF}━━━━━━━━━━━%{T4}%{T-}%{F#67727E}━━━%{F-}"
	elif [ $pc -gt 67 ]
	then
		slider=" %{F#FFFFFF}━━━━━━━━━━%{T4}%{T-}%{F#67727E}━━━━%{F-}"
	elif [ $pc -gt 59 ]
	then
		slider=" %{F#FFFFFF}━━━━━━━━━%{T4}%{T-}%{F#67727E}━━━━━%{F-}"
	elif [ $pc -gt 51 ]
	then
		slider=" %{F#FFFFFF}━━━━━━━━%{T4}%{T-}%{F#67727E}━━━━━━%{F-}"
	elif [ $pc -gt 43 ]
	then
		slider=" %{F#FFFFFF}━━━━━━━%{T4}%{T-}%{F#67727E}━━━━━━━%{F-}"
	elif [ $pc -gt 35 ]
	then
		slider=" %{F#FFFFFF}━━━━━━%{T4}%{T-}%{F#67727E}━━━━━━━━%{F-}"
	elif [ $pc -gt 27 ]
	then
		slider=" %{F#FFFFFF}━━━━━%{T4}%{T-}%{F#67727E}━━━━━━━━━%{F-}"
	elif [ $pc -gt 19 ]
	then
		slider=" %{F#FFFFFF}━━━━%{T4}%{T-}%{F#67727E}━━━━━━━━━━%{F-}"
	elif [ $pc -gt 11 ]
	then
		slider=" %{F#FFFFFF}━━━%{T4}%{T-}%{F#67727E}━━━━━━━━━━━%{F-}"
	elif [ $pc -gt 3 ]
	then
		slider=" %{F#FFFFFF}━━%{T4}%{T-}%{F#67727E}━━━━━━━━━━━━%{F-}"
	elif [ $pc -gt 0 ]
	then
		slider=" %{F#FFFFFF}━%{T4}%{T-}%{F#67727E}━━━━━━━━━━━━━%{F-}"
	else
		slider=" %{T4}%{T-}%{F#67727E}━━━━━━━━━━━━━━%{F-}"
	fi
fi






echo "%{+u +o}%{B-}%{U#272C33} $slider %{B-}%{U-}%{-u -o}"




	

#amixer -c $CARD -M -D $MIXER get Master |
#echo $(sed -n "s/^[^:]*: Playback [0-9]* \[\([0-9]*%\)\] .*/$symbol \1/p" | head -n1)
#echo ""
#echo $(amixer -c $CARD -M -D $MIXER get Master | grep Playback | grep -q off && echo "#F5A3A3" || echo "#EEEEEE")
