#!/usr/bin/env bash

# Author: GekkoP
# Source: http://linuxbbq.org/bbs/viewtopic.php?f=4&t=1656#p33189
 
f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
d=$'\e[1m'
t=$'\e[0m'
v=$'\e[7m'
 
 
cat << EOF
 
 $f1███▊$f2███▊$f3███▊$f4███▊$f5███▊$f6███▊$f7███▊
 $f1███▊$f2███▊$f3███▊$f4███▊$f5███▊$f6███▊$f7███▊
 $f1███▊$f2███▊$f3███▊$f4███▊$f5███▊$f6███▊$f7███▊
 $f1███▊$f2███▊$f3███▊$f4███▊$f5███▊$f6███▊$f7███▊
 $f1███▊$f2███▊$f3███▊$f4███▊$f5███▊$f6███▊$f7███▊
 $f1███▊$f2███▊$f3███▊$f4███▊$f5███▊$f6███▊$f7███▊

EOF
